---
- hosts: all
  vars_files:
    - group_vars/all.yml

  roles:
    - prerequisites
    - setup-nodes

- hosts: k8s_master_0
  vars_files:
    - group_vars/all.yml

  roles:
    - first-master
    - network

- hosts: k8s_master_nodes
  vars_files:
    - group_vars/all.yml

  roles:
    - masters

- hosts: k8s_worker_nodes
  vars_files:
    - group_vars/all.yml

  roles:
    - workers

- hosts: k8s_etcd
  vars_files:
    - group_vars/all.yml

  roles:
    - encrypt-secrets

