---

  - name: Copy Flannel config to master0
    template:
      src: flannel.yaml
      dest: /tmp/flannel.yaml

  - name: Initializing Kubernetes cluster
    shell: kubectl apply -f /tmp/flannel.yaml
