---
  - name: Install open-iscsi on Storage nodes
    apt:
      pkg:
        - open-iscsi
        - libnfs-utils
      state: latest
    become: yes

  - name: Starting and Enabling the required services
    service:
     name: iscsid
     state: started
     enabled: yes
    become: yes

  - name: Add storage-node label
    delegate_to: localhost
    shell: kubectl label nodes {{ inventory_hostname }} node.longhorn.io/create-default-disk=true
    ignore_errors: True


  - name: Add create default disk annotation to node
    delegate_to: localhost
    shell: kubectl annotate nodes {{ inventory_hostname }} node.longhorn.io/default-disks-config='[ { "name":"sasdisk", "path":"/var/lib/longhorn/storage/", "allowScheduling":true, "storageReserved":10485760, "tags":[ "storage", "sasdisk" ] }]'
    ignore_errors: True


  # - name: Fetch longhorn yaml to localhost
  #   fetch:
  #     src: longhorn.yaml
  #     dest: /tmp/longhorn.yaml
  #   run_once: true

  # - name: Kubectl apply -f longhorn.yaml
  #   delegate_to: localhost
  #   shell: kubectl apply -f /tmp/longhorn.yaml
  #   run_once: true
